# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 1ca290ce891b41f341bef34a623b98c3520e773636ad09177d300ac6962cb7cf08c6aefa838243a61fcdf46eb4c37ddf61478bd82742c2e7d9d10b6bf92723e9

test:
  secret_key_base: 4aee770b019c01ef51411e0df73be3f52ac94ae1d8b68e162e8c18f54970681f370322f25f8a346f4bcfbdd79cc4820339912b8e7c230f81cd5fde9d277aa49d

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
